# -*- coding: utf-8 -*-
"""mydemo2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VOiyIrqA87mkaLBS5CEqHz6Y2WqWMz36
"""

!pip install fastapi uvicorn pyngrok nest-asyncio

import nest_asyncio
from pyngrok import ngrok
from fastapi import FastAPI
import uvicorn
import threading
import time

app = FastAPI()
nest_asyncio.apply()

# our token
ngrok.set_auth_token("YOUR_NGROK_TOKEN")

@app.post("/process")
async def process_data(data: dict):
    # كود المعالجة الخاص بنا
    print(f"Received: {data}")
    return {"status": "success", "data": data}

def run_uvicorn():
    uvicorn.run(app, host="0.0.0.0", port=8000)

try:
    ngrok.kill()
except:
    pass

thread = threading.Thread(target=run_uvicorn)
thread.daemon = True
thread.start()

time.sleep(2)

public_url = ngrok.connect(8000).public_url
print(f"\nYour Link:\n{public_url}/process")

# ============================================================
# BLOCK 1 — Upload & Read .txt Files
# PART 1: Data Collection
# ============================================================

from google.colab import files
import zipfile, os, pandas as pd

# رفع ملف الـ zip
uploaded = files.upload()  # اختاري doc1_diabetes.zip

# فك الضغط في مجلد documents_txt
with zipfile.ZipFile("doc1_diabetes.zip", "r") as zip_ref:
    zip_ref.extractall("documents_txt")

# قراءة الملفات وتخزينها في DataFrame
docs = []
for filename in sorted(os.listdir("documents_txt")):
    if filename.endswith(".txt"):
        with open(f"documents_txt/{filename}", "r", encoding="utf-8") as f:
            docs.append({"filename": filename, "text": f.read()})

df = pd.DataFrame(docs)

print(f"✅ عدد الملفات المقروءة: {len(df)} (يجب أن يكون 30)")
print(f"✅ أسماء الأعمدة: {list(df.columns)}")
print("-" * 50)
print(df[['filename']].to_string(index=False))

# ============================================================
# BLOCK 2 — Tokenization & Stopword Removal
# PART 1: Preprocessing Step 1
# ============================================================

import nltk, string
from nltk.corpus import stopwords

nltk.download('stopwords')

stop_words = set(stopwords.words('english'))

def tokenize_and_remove_stopwords(text):
    # lowercase
    text = text.lower()
    # إزالة علامات الترقيم
    text = text.translate(str.maketrans('', '', string.punctuation))
    # تقسيم إلى كلمات (Tokenization)
    tokens = text.split()
    # حذف الـ stopwords والأرقام
    tokens = [w for w in tokens if w not in stop_words and not w.isdigit()]
    return tokens

df['tokens'] = df['text'].apply(tokenize_and_remove_stopwords)

print("✅ تم تطبيق Tokenization و Stopword Removal")
print("-" * 50)
print("📄 مثال — أول مستند:")
print(f"Filename : {df['filename'].iloc[0]}")
print(f"Tokens   : {df['tokens'].iloc[0][:15]} ...")
print(f"عدد الكلمات بعد التنظيف: {len(df['tokens'].iloc[0])}")

# ============================================================
# BLOCK 3 — Lemmatization
# PART 1: Preprocessing Step 2
# ============================================================

from nltk.stem import WordNetLemmatizer

nltk.download('wordnet')
nltk.download('omw-1.4')

lemmatizer = WordNetLemmatizer()

def lemmatize_tokens(tokens):
    return [lemmatizer.lemmatize(w) for w in tokens]

df['lemmatized_tokens'] = df['tokens'].apply(lemmatize_tokens)

# دمج الكلمات في نص واحد نظيف جاهز للـ TF-IDF
df['cleaned_text'] = df['lemmatized_tokens'].apply(lambda tokens: " ".join(tokens))

print("✅ تم تطبيق Lemmatization")
print("-" * 50)
print("📄 مثال — مقارنة قبل وبعد:")
print(f"قبل  : {df['tokens'].iloc[3][:8]}")
print(f"بعد  : {df['lemmatized_tokens'].iloc[3][:8]}")
print(f"\nNص نظيف جاهز: {df['cleaned_text'].iloc[3][:80]}...")

# ============================================================
# طباعة كل الكلمات من جميع الملفات بشكل مرتب
# ============================================================

# جمع كل الكلمات بعد الـ Lemmatization من جميع الملفات
all_words = []
for _, row in df.iterrows():
    all_words.extend(row['lemmatized_tokens'])

# ترتيب أبجدي وإزالة التكرار
unique_words = sorted(set(all_words))

print("\n" + "=" * 60)
print(f"📚 جميع الكلمات الفريدة بعد المعالجة — الإجمالي: {len(unique_words)} كلمة")
print("=" * 60)

# طباعة بشكل عمودي منظم (5 كلمات في كل صف)
cols = 5
for i in range(0, len(unique_words), cols):
    row_words = unique_words[i:i+cols]
    print("  ".join(f"{w:<18}" for w in row_words))

print("=" * 60)
print(f"✅ إجمالي الكلمات الفريدة: {len(unique_words)}")
print(f"✅ إجمالي الكلمات الكلي (مع التكرار): {len(all_words)}")

## ============================================================
# BLOCK 4 — TF-IDF Term/Document Matrix
# PART 1: Indexing
# ============================================================

from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(df['cleaned_text'])
feature_names = vectorizer.get_feature_names_out()

print(f"✅ تم بناء مصفوفة TF-IDF")
print(f"   الأبعاد: {tfidf_matrix.shape[0]} مستند × {tfidf_matrix.shape[1]} مصطلح")
print("-" * 50)

# تحويل المصفوفة إلى DataFrame مرتب
tfidf_df = pd.DataFrame(
    tfidf_matrix.toarray(),
    index=df['filename'],
    columns=feature_names
)

# إعدادات العرض
pd.set_option('display.float_format', '{:.6f}'.format)
pd.set_option('display.max_columns', 20)
pd.set_option('display.width', 200)

print("\n📊 مصفوفة TF-IDF الكاملة (كل المستندات × كل المصطلحات):")
print("=" * 60)
print(tfidf_df.to_string())

# ============================================================
# BLOCK 4 — TF-IDF Term/Document Matrix
# PART 1: Indexing
# ============================================================

from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(df['cleaned_text'])
feature_names = vectorizer.get_feature_names_out()

print(f"✅ تم بناء مصفوفة TF-IDF")
print(f"   الأبعاد: {tfidf_matrix.shape[0]} مستند × {tfidf_matrix.shape[1]} مصطلح")
print("-" * 50)

# تحويل المصفوفة إلى DataFrame
tfidf_df = pd.DataFrame(
    tfidf_matrix.toarray(),
    index=df['filename'],
    columns=feature_names
)

# أعلى 10 كلمات بالأوزان الإجمالية
top_words = tfidf_df.sum().sort_values(ascending=False).head(10).index.tolist()

pd.set_option('display.float_format', '{:.6f}'.format)

print("\n📊 مصفوفة TF-IDF — أعلى 10 مصطلحات:")
print("=" * 80)
print(tfidf_df[top_words].to_string())

# ============================================================
# BLOCK 5 — Information Retrieval (Cosine Similarity)
# PART 2: Query & Ranked Results
# ============================================================

from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

# --- الاستعلام الأول ---
query1 = "symptoms of diabetes and blood sugar levels"

def retrieve(query, top_n=5):
    query_clean = " ".join([
        lemmatizer.lemmatize(w) for w in query.lower()
        .translate(str.maketrans('', '', string.punctuation))
        .split() if w not in stop_words
    ])
    query_vec = vectorizer.transform([query_clean])
    scores = cosine_similarity(query_vec, tfidf_matrix).flatten()
    ranked = np.argsort(scores)[::-1]
    return ranked, scores

ranked1, scores1 = retrieve(query1)

print(f"🔍 Query 1: '{query1}'")
print("-" * 45)
print(f"{'Rank':<6} {'Filename':<30} {'Score':<10}")
print("-" * 45)
for rank, idx in enumerate(ranked1[:5], 1):
    print(f"{rank:<6} {df['filename'].iloc[idx]:<30} {scores1[idx]:.4f}")

# --- الاستعلام الثاني ---
query2 = "movie review film actors performance"
ranked2, scores2 = retrieve(query2)

print(f"\n🔍 Query 2: '{query2}'")
print("-" * 45)
print(f"{'Rank':<6} {'Filename':<30} {'Score':<10}")
print("-" * 45)
for rank, idx in enumerate(ranked2[:5], 1):
    print(f"{rank:<6} {df['filename'].iloc[idx]:<30} {scores2[idx]:.4f}")

# ============================================================
# BLOCK 6 — Precision & Recall
# PART 2: Performance Evaluation
# ============================================================

# القيم الصحيحة لكل مستند (Medical = doc1 إلى doc15)
medical_files = {f"doc{i}_" for i in range(1, 16)}

def is_medical(filename):
    return any(filename.startswith(prefix) for prefix in medical_files)

# --- تقييم Query 1 (متعلق بـ Medical) ---
top5_query1 = [df['filename'].iloc[i] for i in ranked1[:5]]
relevant_retrieved_q1 = sum(1 for f in top5_query1 if is_medical(f))
total_medical = sum(1 for f in df['filename'] if is_medical(f))  # = 15

precision_q1 = relevant_retrieved_q1 / 5
recall_q1    = relevant_retrieved_q1 / total_medical

print("📊 تقييم Query 1 — 'diabetes & blood sugar'")
print("-" * 40)
print(f"  Relevant retrieved : {relevant_retrieved_q1} / 5")
print(f"  Precision @ 5      : {precision_q1:.2f}")
print(f"  Recall @ 5         : {recall_q1:.2f}")

# --- تقييم Query 2 (متعلق بـ Non-Medical) ---
non_medical_files = {f"doc{i}_" for i in range(16, 31)}
def is_nonmedical(filename):
    return any(filename.startswith(prefix) for prefix in non_medical_files)

top5_query2 = [df['filename'].iloc[i] for i in ranked2[:5]]
relevant_retrieved_q2 = sum(1 for f in top5_query2 if is_nonmedical(f))
total_nonmedical = 15

precision_q2 = relevant_retrieved_q2 / 5
recall_q2    = relevant_retrieved_q2 / total_nonmedical

print("\n📊 تقييم Query 2 — 'movie review film'")
print("-" * 40)
print(f"  Relevant retrieved : {relevant_retrieved_q2} / 5")
print(f"  Precision @ 5      : {precision_q2:.2f}")
print(f"  Recall @ 5         : {recall_q2:.2f}")

# ============================================================
# BLOCK 6 — Precision & Recall
# PART 2: Performance Evaluation
# ============================================================

medical_files = {f"doc{i}_" for i in range(1, 16)}
non_medical_files = {f"doc{i}_" for i in range(16, 31)}

def is_medical(filename):
    return any(filename.startswith(prefix) for prefix in medical_files)

def is_nonmedical(filename):
    return any(filename.startswith(prefix) for prefix in non_medical_files)

total_medical    = sum(1 for f in df['filename'] if is_medical(f))
total_nonmedical = sum(1 for f in df['filename'] if is_nonmedical(f))

# ══════════════════════════════════════
# Query 1 — Medical
# ══════════════════════════════════════
top5_query1 = [df['filename'].iloc[i] for i in ranked1[:5]]
relevant_retrieved_q1 = sum(1 for f in top5_query1 if is_medical(f))

precision_q1 = relevant_retrieved_q1 / 5
recall_q1    = relevant_retrieved_q1 / total_medical

print("📊 تقييم Query 1 — 'diabetes & blood sugar'")
print("-" * 50)
print(f"  {'المقياس':<30} {'القيمة'}")
print("-" * 50)
print(f"  {'Total Relevant (في الكورباس)':<30} {total_medical}")
print(f"  {'Total Retrieved':<30} 5")
print(f"  {'Relevant & Retrieved':<30} {relevant_retrieved_q1}")
print(f"  {'Precision @ 5':<30} {precision_q1:.2f}")
print(f"  {'Recall @ 5':<30} {recall_q1:.2f}")
print("-" * 50)
print("  📄 المستندات المسترجعة:")
for rank, f in enumerate(top5_query1, 1):
    tag = "✅ Relevant" if is_medical(f) else "❌ Not Relevant"
    print(f"     {rank}. {f:<30} {tag}")

# ══════════════════════════════════════
# Query 2 — Non-Medical
# ══════════════════════════════════════
top5_query2 = [df['filename'].iloc[i] for i in ranked2[:5]]
relevant_retrieved_q2 = sum(1 for f in top5_query2 if is_nonmedical(f))

precision_q2 = relevant_retrieved_q2 / 5
recall_q2    = relevant_retrieved_q2 / total_nonmedical

print("\n📊 تقييم Query 2 — 'movie review film'")
print("-" * 50)
print(f"  {'المقياس':<30} {'القيمة'}")
print("-" * 50)
print(f"  {'Total Relevant (في الكورباس)':<30} {total_nonmedical}")
print(f"  {'Total Retrieved':<30} 5")
print(f"  {'Relevant & Retrieved':<30} {relevant_retrieved_q2}")
print(f"  {'Precision @ 5':<30} {precision_q2:.2f}")
print(f"  {'Recall @ 5':<30} {recall_q2:.2f}")
print("-" * 50)
print("  📄 المستندات المسترجعة:")
for rank, f in enumerate(top5_query2, 1):
    tag = "✅ Relevant" if is_nonmedical(f) else "❌ Not Relevant"
    print(f"     {rank}. {f:<30} {tag}")

# ============================================================
# BLOCK 7 — Manual Labeling
# PART 3: Label each document manually
# ============================================================

import re

def assign_label(filename):
    # استخراج الرقم بأمان بغض النظر عن - أو _
    match = re.search(r'doc(\d+)', filename)
    if match:
        num = int(match.group(1))
        return "Medical" if num <= 15 else "Non-Medical"
    return "Unknown"

df['label'] = df['filename'].apply(assign_label)

# حفظ بالصيغة المطلوبة: Document ID, Document Text, Label
labeled_df = df[['filename', 'text', 'label']].copy()
labeled_df.columns = ['Document ID', 'Document Text', 'Label']
labeled_df.to_csv("labeled_documents.csv", index=False)

print("✅ تم التصنيف اليدوي وحفظ الملف 'labeled_documents.csv'")
print("-" * 50)
print(f"{'Document ID':<30} {'Label':<15}")
print("-" * 50)
print(labeled_df[['Document ID', 'Label']].to_string(index=False))

# ============================================================
# BLOCK 8 — Naive Bayes Classification
# PART 3: Train, Predict, Evaluate
# ============================================================

from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report
import pandas as pd

X = tfidf_matrix
y = df['label']

# تقسيم البيانات 60% تدريب و40% اختبار
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.4, random_state=0
)

print(f"✅ تقسيم البيانات:")
print(f"   Training set : {X_train.shape[0]} مستند")
print(f"   Testing set  : {X_test.shape[0]} مستند")
print("-" * 40)

clf = MultinomialNB()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print(f"🎯 Naive Bayes Classification Results")
print("-" * 40)
print(f"  Accuracy : {accuracy * 100:.2f}%")
print("-" * 40)
print(classification_report(y_test, y_pred))

# جدول النتائج الكاملة لكل 30 مستند
all_preds = clf.predict(tfidf_matrix)
result_df = pd.DataFrame({
    'Document':  df['filename'],
    'Actual':    df['label'],
    'Predicted': all_preds,
    'Correct':   ['✅' if a == p else '❌' for a, p in zip(df['label'], all_preds)]
})
print("📋 نتائج التصنيف لكل المستندات:")
print(result_df.to_string(index=False))
# ============================================================
# BLOCK 8C — Confusion Matrix for Naive Bayes
# ============================================================
print(f"بيانات الاختبار")
test_results = pd.DataFrame({
    'Actual': y_test.values,
    'Predicted': y_pred
})

print(test_results.to_string(index=False))
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

cm_nb = confusion_matrix(y_test, y_pred, labels=clf.classes_)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm_nb,
    display_labels=clf.classes_
)

disp.plot(cmap="Blues", values_format="d")
plt.title("Confusion Matrix - Naive Bayes")
plt.show()

# ============================================================
# BLOCK 8B — Decision Tree Classification
# PART 3: Alternative Classifier
# ============================================================

from sklearn.tree import DecisionTreeClassifier

dt_clf = DecisionTreeClassifier(random_state=42)
dt_clf.fit(X_train, y_train)
dt_pred = dt_clf.predict(X_test)

dt_accuracy = accuracy_score(y_test, dt_pred)

print(f"🌳 Decision Tree Classification Results")
print("-" * 40)
print(f"  Accuracy : {dt_accuracy * 100:.2f}%")
print("-" * 40)
print(classification_report(y_test, dt_pred))

# جدول النتائج الكاملة لكل 30 مستند
dt_all_preds = dt_clf.predict(tfidf_matrix)
dt_result_df = pd.DataFrame({
    'Document':  df['filename'],
    'Actual':    df['label'],
    'Predicted': dt_all_preds,
    'Correct':   ['✅' if a == p else '❌' for a, p in zip(df['label'], dt_all_preds)]
})
print("📋 نتائج التصنيف لكل المستندات:")
print(dt_result_df.to_string(index=False))

# مقارنة بين الموديلين
print("\n📊 مقارنة بين الموديلين:")
print("-" * 40)
print(f"  Naive Bayes   : {accuracy * 100:.2f}%")
print(f"  Decision Tree : {dt_accuracy * 100:.2f}%")
# ============================================================
# BLOCK 8D — Confusion Matrix for Decision Tree
# ============================================================
print(f"بيانات الاختبار")
test_results = pd.DataFrame({
    'Filename': df.iloc[y_test.index]['filename'].values,
    'Actual': y_test.values,
    'Predicted': y_pred
})

print(test_results.to_string(index=False))


cm_dt = confusion_matrix(y_test, dt_pred, labels=dt_clf.classes_)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm_dt,
    display_labels=dt_clf.classes_
)

disp.plot(cmap="Greens", values_format="d")
plt.title("Confusion Matrix - Decision Tree")
plt.show()

# ============================================================
# BLOCK 9 — K-means Clustering
# PART 4: Unsupervised — Data must NOT use labels
# ============================================================

from sklearn.cluster import KMeans
from sklearn.metrics import accuracy_score
from sklearn.decomposition import TruncatedSVD

# تقليل الأبعاد أولاً لتحسين الـ Clustering
svd = TruncatedSVD(n_components=50, random_state=42)
reduced_matrix = svd.fit_transform(tfidf_matrix)

# K-means على البيانات المخفضة
kmeans = KMeans(n_clusters=2, random_state=42, n_init=20, max_iter=500)
cluster_labels = kmeans.fit_predict(reduced_matrix)

df['cluster'] = cluster_labels

# بعد الـ Clustering نقارن مع الـ ground truth لحساب الدقة
true_labels = df['label'].map({'Medical': 1, 'Non-Medical': 0})

acc = accuracy_score(true_labels, df['cluster'])
# تصحيح إذا كانت الأرقام معكوسة
if acc < 0.5:
    df['cluster'] = df['cluster'].map({0: 1, 1: 0})
    acc = accuracy_score(true_labels, df['cluster'])

print(f"📊 K-means Clustering Results")
print("-" * 40)
print(f"  Clustering Accuracy: {acc * 100:.2f}%")
print("-" * 40)
print(df[['filename', 'label', 'cluster']].to_string(index=False))

summary = df.groupby(['cluster', 'label']).size().unstack(fill_value=0)
print("\n📋 توزيع المستندات على العناقيد:")
print(summary)
# ============================================================
# BLOCK 9B — Confusion Matrix for K-means Clustering
# ============================================================

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

true_cluster_labels = df['label'].map({'Medical': 1, 'Non-Medical': 0})

cm_kmeans = confusion_matrix(true_cluster_labels, df['cluster'], labels=[1, 0])

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm_kmeans,
    display_labels=['Medical', 'Non-Medical']
)

disp.plot(cmap="Purples", values_format="d")
plt.title("Confusion Matrix - K-means Clustering")
plt.show()

# ============================================================
# BLOCK 10 — Clustering Visualization with Class Circles
# ============================================================

import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from matplotlib.patches import Ellipse
import numpy as np
import pandas as pd

# تحويل reduced_matrix إلى 2D للرسم فقط
pca = PCA(n_components=2, random_state=42)
reduced_2d_plot = pca.fit_transform(reduced_matrix)

plot_df = pd.DataFrame({
    "x": reduced_2d_plot[:, 0],
    "y": reduced_2d_plot[:, 1],
    "filename": df["filename"],
    "label": df["label"],
    "cluster": df["cluster"]
})

plt.figure(figsize=(13, 8))
ax = plt.gca()

colors = {
    "Medical": "orange",
    "Non-Medical": "steelblue"
}

# رسم النقاط حسب الكلاس الحقيقي
for label in ["Medical", "Non-Medical"]:
    subset = plot_df[plot_df["label"] == label]

    ax.scatter(
        subset["x"],
        subset["y"],
        s=110,
        alpha=0.85,
        color=colors[label],
        label=label,
        edgecolors="white",
        linewidths=0.8
    )

    # دائرة/بيضاوي حول كل كلاس
    center_x = subset["x"].mean()
    center_y = subset["y"].mean()

    width = (subset["x"].max() - subset["x"].min()) * 1.25
    height = (subset["y"].max() - subset["y"].min()) * 1.35

    ellipse = Ellipse(
        (center_x, center_y),
        width=width,
        height=height,
        fill=False,
        edgecolor=colors[label],
        linewidth=2.5,
        linestyle="--"
    )

    ax.add_patch(ellipse)

# كتابة أسماء الملفات
for i, row in plot_df.iterrows():
    ax.annotate(
        row["filename"].replace(".txt", ""),
        (row["x"], row["y"]),
        xytext=(6, 6),
        textcoords="offset points",
        fontsize=8
    )

plt.title("Document Distribution by Class with Class Boundaries", fontsize=14, fontweight="bold")
plt.xlabel("PCA Component 1")
plt.ylabel("PCA Component 2")
plt.legend()
plt.grid(True, linestyle="--", alpha=0.4)
plt.tight_layout()
plt.savefig("class_circles_plot.png", dpi=150, bbox_inches="tight")
plt.show()

print("📋 توزيع الـ Clusters داخل كل Class:")
print(pd.crosstab(df["label"], df["cluster"]))

# ============================================================
# BLOCK 12A — Test: Document Retrieval
# ============================================================

query = input("🔍 أدخلي الاستعلام (Query): ").strip()

query_clean = " ".join([
    lemmatizer.lemmatize(w) for w in query.lower()
    .translate(str.maketrans('', '', string.punctuation))
    .split() if w not in stop_words
])

query_vec = vectorizer.transform([query_clean])
scores = cosine_similarity(query_vec, tfidf_matrix).flatten()
ranked = np.argsort(scores)[::-1]

# عدد المستندات المسترجعة فوق threshold
threshold = 0.1
retrieved = [i for i in ranked if scores[i] > threshold]

print(f"\n🔍 نتائج البحث عن: '{query}'")
print(f"📂 عدد المستندات المسترجعة (score > {threshold}): {len(retrieved)}")
print("-" * 60)
print(f"{'Rank':<6} {'Filename':<30} {'Label':<15} {'Confidence'}")
print("-" * 60)
for rank, idx in enumerate(ranked[:5], 1):
    confidence = scores[idx] * 100
    print(f"{rank:<6} {df['filename'].iloc[idx]:<30} {df['label'].iloc[idx]:<15} {confidence:.3f}%")

# ============================================================
# BLOCK 12B — Test: Classification
# ============================================================

text = input("🏷️ أدخلي نص المستند: ").strip()


text_clean = " ".join([
    lemmatizer.lemmatize(w) for w in text.lower()
    .translate(str.maketrans('', '', string.punctuation))
    .split() if w not in stop_words
])

text_vec = vectorizer.transform([text_clean])
predicted = clf.predict(text_vec)[0]
proba = clf.predict_proba(text_vec)[0]
confidence = max(proba) * 100


print(f"\n🏷️ نتيجة التصنيف:")
print("-" * 40)


print(f"  نسبة الثقة       : {confidence:.2f}%")
print("-" * 40)
for label, prob in zip(clf.classes_, proba):
    bar = '█' * int(prob * 20)
    print(f"  {label:<15} : {prob*100:.2f}%  {bar}")

from sklearn.metrics.pairwise import euclidean_distances
import numpy as np

text = input("📊 أدخلي نص المستند: ").strip()


# تنظيف النص
text_clean = " ".join([
    lemmatizer.lemmatize(w) for w in text.lower()
    .translate(str.maketrans('', '', string.punctuation))
    .split() if w not in stop_words
])

# TF-IDF + SVD
text_vec = vectorizer.transform([text_clean])
text_reduced = svd.transform(text_vec)

# التنبؤ بالـ cluster
cluster_pred = kmeans.predict(text_reduced)[0]

# معنى الكلستر
cluster_meaning = df.groupby('cluster')['label'].agg(
    lambda x: x.value_counts().index[0]
)
cluster_name = cluster_meaning[cluster_pred]

# ====================================================
# Distance → Percentage Conversion
# ====================================================

distances = euclidean_distances(text_vec, tfidf_matrix).flatten()

similarity_percentage = 100 * (1 / (1 + distances))

ranked = np.argsort(similarity_percentage)[::-1][:5]

avg_similarity = similarity_percentage[ranked].mean()

# تحقق
correct = '✅' if cluster_name == true_label else '❌'

# ====================================================
# Output
# ====================================================

print(f"\n📊 نتيجة التجميع (Similarity %):")
print("-" * 50)

print(f"  Cluster المحدد   : Cluster {cluster_pred} ({cluster_name})  {correct}")
print(f"  متوسط التشابه    : {avg_similarity:.2f}%")
print("-" * 50)

print("📂 أقرب 5 مستندات:")
for idx in ranked:
    print(f"  {df['filename'].iloc[idx]:<30} | Similarity: {similarity_percentage[idx]:.2f}%")

import json
from google.colab import output

def assess_severity(symptoms_count, duration_str):
    """
    تقييم خطورة الحالة بناءً على عدد الأعراض ومدة المرض
    """
    # تحويل المدة لرقم (أيام)
    duration_days = 0
    if duration_str:
        d = duration_str.lower()
        if "less than 1" in d:
            duration_days = 0.5
        elif "1–3" in d or "1-3" in d:
            duration_days = 2
        elif "4–7" in d or "4-7" in d:
            duration_days = 5
        elif "1–2 weeks" in d or "1-2 weeks" in d:
            duration_days = 10
        elif "more than 2" in d:
            duration_days = 20

    # منطق التقييم
    if symptoms_count <= 1 and duration_days <= 2:
        level = "low"
        label = "حالة طبيعية"
        label_en = "Normal"
        desc = "الأعراض خفيفة ولا تستدعي القلق. راقبي الوضع."
        color = "#5BB8A6"
        icon = "🟢"

    elif symptoms_count == 2 or (symptoms_count <= 3 and duration_days <= 5):
        level = "moderate"
        label = "خطورة متوسطة"
        label_en = "Moderate Risk"
        desc = "الأعراض تستدعي الانتباه. يُنصح بالراحة ومتابعة الحالة."
        color = "#D4A840"
        icon = "🟡"

    elif symptoms_count >= 3 and duration_days >= 5:
        level = "critical"
        label = "حالة حرجة"
        label_en = "Critical"
        desc = "الأعراض متعددة وممتدة. يجب مراجعة الطبيب فوراً."
        color = "#D45878"
        icon = "🔴"

    else:
        level = "warning"
        label = "تحتاج متاب<seg_125>لعة"
        label_en = "Needs Attention"
        desc = "راجعي الطبيب إذا استمرت الأعراض أكثر من يومين."
        color = "#E07850"
        icon = "🟠"

    return {
        "level": level,
        "label": label,
        "label_en": label_en,
        "desc": desc,
        "color": color,
        "icon": icon,
        "symptoms_count": symptoms_count,
        "duration_days": duration_days
    }

# ثم سجّليها كـ callback بعد الدوال الثانية:
output.register_callback('assess', lambda s, d: output.eval_js(
    f'showSeverity({json.dumps(assess_severity(int(s), d))})'))